### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by Toastbroad** [mrvilla/collection#1]
https://github.com/mrvilla/collection/blob/fc2f42d057590389ce0088c9507eae0217494e0a/src/app/shared/data/externtalData.js#L4

What about error handling here? If one of the `fetch`es throws an error, the entire `Promise.all` fails also. This can be avoided :)

**Comment by einkauf-aperto** [comment]
@Toastbroad this totally makes sense. Already added it. Helps to view which api is not working correctly.

**Comment by mrvilla** [comment]
@Toastbroad yes, added a catch to each fetch. found out that my comicvine api does not work locally.

**Comment by mrvilla** [comment]
thanks again! QL

**Comment by mrvilla** [comment]
thanks again! QL

**Comment by mrvilla** [comment]
thanks again! QL

**Comment by mrvilla** [comment]
thanks again! QL
