### ISSUE TITLE
Low level ajax call

### ISSUE THREAD

**Issue by Toastbroad** [mrvilla/collection#2]
https://github.com/mrvilla/collection/blob/fc2f42d057590389ce0088c9507eae0217494e0a/src/app/shared/data/externtalData.js#L18-L33

Are we doing anything with this? We don't need to go so low-level here, because `fetch` abstracts all of that away.

**Comment by mrvilla** [comment]
@Toastbroad your right i ended up removing it

**Comment by mrvilla** [comment]
cool gQL
